<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Uday" failures="3" tests="3" name="BankingApp Test(failed)" time="42.421" errors="0" timestamp="2022-03-24T04:37:47 IST">
  <testcase classname="com.inetBankingV1.testCases.TC_LoginDDT_002" name="loginDDT" time="5.651">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBankingV1.testCases.TC_LoginDDT_002" name="loginDDT" time="5.162">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
  <testcase classname="com.inetBankingV1.testCases.TC_LoginDDT_002" name="loginDDT" time="6.132">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.inetBankingV1.testCases.TC_LoginDDT_002.loginDDT(TC_LoginDDT_002.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginDDT -->
</testsuite> <!-- BankingApp Test(failed) -->
